# Generated by Django 5.0 on 2023-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noc_transfer',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
