# Generated by Django 5.0 on 2023-12-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topups',
            name='topup_method',
            field=models.CharField(choices=[('alfamart', 'Alfamart'), ('indomart', 'Indomart'), ('lawson', 'Lawson'), ('dana', 'Dana'), ('ovo', 'OVO'), ('gopay', 'GoPay'), ('linkaja', 'LinkAja'), ('jenius', 'Jenius'), ('fastpay', 'FastPay'), ('kudo', 'Kudo'), ('bri', 'BRI'), ('mandiri', 'Mandiri'), ('bca', 'BCA'), ('bni', 'BNI'), ('bukopin', 'Bukopin'), ('e-banking', 'E-Banking'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover'), ('american express', 'American Express'), ('paypal', 'PayPal')], max_length=255),
        ),
    ]
