# Generated by Django 5.0 on 2023-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0003_alter_topups_topup_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topups',
            name='topup_amount',
            field=models.BigIntegerField(default='bfc-49353166157241453'),
        ),
    ]
