# Generated by Django 5.0 on 2023-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0004_alter_topups_topup_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topups',
            name='topup_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='topups',
            name='topup_no',
            field=models.CharField(default='bfc-430513370302928167', max_length=255),
        ),
    ]
